export type OpCode = 'push'
                   | 'pop'
                   | 'inc'
                   | 'dec'
                   | 'add'
                   | 'sub'
                   | 'mul'
                   | 'div'
                   | 'pow'
                   | 'noop' 
                   | 'store' 
                   | 'load'
                   | 'cmp'
                   | 'cmp_gt'
                   | 'cmp_lt'
                   | 'cmp_eq'
                   | 'jump'
                   | 'jump_if_gt'
                   | 'jump_if_zero'
                   | 'swap'
                   | 'call'
                   | 'invoke'
                   | 'ret'
                   ;
